// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFPKyC2GTRcn1L2NH9KcHhDtIv-SNUjG4',
    appId: '1:609550492956:android:6bbc7e0dd792c15dc146d9',
    messagingSenderId: '609550492956',
    projectId: 'yamaitre-fc7ea',
    databaseURL: 'https://yamaitre-fc7ea-default-rtdb.firebaseio.com',
    storageBucket: 'yamaitre-fc7ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY8_tgIPAdn9SBwIUEZ49oWUWtLtarJ_0',
    appId: '1:609550492956:ios:317b48d8f8979d51c146d9',
    messagingSenderId: '609550492956',
    projectId: 'yamaitre-fc7ea',
    databaseURL: 'https://yamaitre-fc7ea-default-rtdb.firebaseio.com',
    storageBucket: 'yamaitre-fc7ea.appspot.com',
    iosClientId: '609550492956-o2ipnimtubl9k1kq644ofotqj4hfdpnr.apps.googleusercontent.com',
    iosBundleId: 'com.primax.yamaiter.yamaiter',
  );
}
